#!/bin/bash


export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
#adb uninstall free.rm.skytube.oss
#rm ./app/build -fr 
./gradlew assembleDebug 
adb install app/build/outputs/apk/debug/app-debug.apk
