name: CI

on: [push, pull_request]

jobs:


    buildDebug:
        name: Debug build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3

            - name: Run debug build
              run: ./gradlew assembleDebug

            - name: Upload APK
              uses: actions/upload-artifact@v3
              with:
                name: app
                path: app/build/outputs/apk/debug/app-debug.apk
